language: node_js
node_js:
  - '4.2'
before_install:
  - npm i -g npm@2
install:
  - npm install
script: null
before_deploy: "rm -f cloudbot.zip && zip cloudbot.zip -r * -x .\\* node_modules/\\* cloudbot.zip"
deploy:
  provider: releases
  api_key: "$GH_OAUTH_TOKEN"
  file: "cloudbot.zip"
  skip_cleanup: true
  on:
    tags: true
notifications:
  webhooks: 'http://cloud-solutions-travis.mybluemix.net/notifications'
